### PR TITLE
Made Docker build running again

### PR DESCRIPTION
**Pull request by piccobit**
- Copy 'package.json' instead 'server-package.json'
- Use 'production' environment

### CODE REVIEW

**Comment by zadam** [comment]
Hi, I don't understand these changes - docker build is running for me OK.

Also why changing npm scripts - those are for development and not for production use.

**Comment by piccobit** [comment]
Hi, apologies for the confusion but I just wanted to test the newest bugfixes and features and didn't find a Dockerfile in your official repository on the Docker hub. Therefore I tried the one here in your GitHub repository and immediately noticed that it didn't work because your repository doesn't contain a file called 'server-package.json' at all. ;-)

So, if the Dockerfile in your repository is only needed for the development, where do I find the one you're using the build the production Docker image?

**Comment by zadam** [comment]
If you want to build docker image, run `bin/build-docker.sh` - that will correctly generate the missing `server-package.json`

Reason for this is that server version doesn't need some package dependencies like electron so we don't include those in the docker build.

**Comment by piccobit** [comment]
OMG, didn't see that!

Thanks for the explanation, I'll close this PR now...

**Pull request closed without merging**
