### PR TITLE
New Theme: Rainbow in the Dark

### PR DESCRIPTION
**Pull request by Abourass**
While working on the math plugin for CKEditor I created the following theme, figured I'd open a PR, and it can be merged if you want, if not, no worries feel free to close. 

Sample Theme

### CODE REVIEW

**Comment by zadam** [comment]
Hello, that looks interesting :-) I want to include some more built in color themes but using only the "exposed interface" (essentially defined variables) because if a theme uses CSS selectors then it will be too difficult to maintain when HTML structure will change in the future.

But I also plan to add some easier way to develop and use custom themes - e.g. CSS note with `@appTheme` label would automatically show up in the theme select box in options. This might then be provided as an exported note in .tar archive.

So instead of merging this, what about creating a separate repo and I can link to it from [wiki page on themes](https://github.com/zadam/trilium/wiki/Themes)?

**Comment by Abourass** [comment]
Something like [this?](https://github.com/Abourass/RainbowInTheDarkTril/blob/master/theme.css)
Not sure if the variable declaration will work still, and I know I can't import font via @import within the @appTheme file, so codeLens wont use the font I'd declared. 
Maybe something like you did for font size with custom fonts? 
Because I must admit I love using Raleway
Example Code Image

**Comment by gerroon** [comment]
How do I apply this in docker?

**Comment by zadam** [comment]
Yes, even though I don't think that providing modified builds is sustainable in the future. 

As I understand the main reason for this is to provide extra fonts? I think it might be possible to include a generic functionality where you would mark a note (in this case file note with uploaded) with a label which would expose it on the HTTP level so you could link to it from CSS. This is actually planned for 0.29 and comes originally from #356.

Anyway I included a link to your repo to this page: https://github.com/zadam/trilium/wiki/Themes

**Comment by Abourass** [comment]
@zadam I agree. 

I will remove the modified builds shortly, while keeping the installation instructions for the @appCss attribute method, and the replacing files then build on their own method (until v0.29 is released, then I will modify it too only be the @appCss option). 

It is indeed to provide a single extra font. The solution you just outlined seems perfect. I would think that would also allow custom icons which is exciting. I apologize if my request (for fonts) is a tad tedious. 

I will close this issue now. Thanks.

**Pull request closed without merging**
