### PR TITLE
Update webmanifest for wider compatibility

### LINKED ISSUE #920: PWA Support
Is there PWA support in the plans for Trilium?
I see a lot of potential for custom server deployed solutions and relatively simple to implement.

Possibly Even Utilize the features service worker provide

### PR DESCRIPTION
**Pull request by rauenzi**
Partially fixes #920, just does not enable offline usage.

### CODE REVIEW

**Comment by rauenzi** [comment]
By the way, let me know if you want me to work on offline usage for PWA, after toying around with it some is may be *mostly* possible.

**Comment by zadam** [comment]
> By the way, let me know if you want me to work on offline usage for PWA, after toying around with it some is may be mostly possible.

Sure, although I'm curious what that "mostly" means :-)

**Comment by rauenzi** [comment]
Some caveats would be:
1. If the user goes offline there would be no way for them to get/open existing notes that have not already been cached in some way. (i.e. viewing the note when they were online)
2. Any functionality not already cached like the different language extensions for codemirror will be lost during offline mode.
3. Users would not be able to create new notes

Number 1 can't really be worked around without explicitly attempting to cache every single note on first install, which is technically possible but can also lead to a lot of stale information.

Number 2 can be worked around by pre-caching all the _potential_ resources like that though it is a bit of a pain to do.

Number 3 can't be worked around without actual changes to Trilium.


So either way I think a network-first approach is the right one for Trilium, and combine this with some updates to the mobile interface (#3975, #4335) I think that would alleviate a lot of the calls for a "proper" mobile app.

**Comment by zadam** [comment]
> So either way I think a network-first approach is the right one for Trilium

Agreed.

**Comment by dahamsta** [comment]
Thanks for this. Would I be right in saying that this wasn't rolled into 0.61.12?

**Comment by rauenzi** [comment]
This was merged into main which will become 0.62

**Comment by dahamsta** [comment]
Great, thanks, I'll test as soon as I get it.

**Comment by rauenzi** [comment]
You could modify your existing container to match this change and test for yourself if you're using Docker. Might be worth moving this part to a discussion though if you're interested.

**Comment by jacksgt** [comment]
Thanks for this awesome work! I can confirm that it works with Trilium v.0.62.3 on Firefox for Android. :clap:

**Comment by dahamsta** [comment]
Same, lovely job, thanks.

**Pull request merged**
