### PR TITLE
Add support for importing math expressions from Markdown

### LINKED ISSUE #4387: (Bug report) math formula format incorrectly
### Trilium Version

0.61.12

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows10 22H2

### Description

When importing `.md` files with math formula, their style was lost, or infact, the Trilium Note does't support the `.md` style math formula like this:
图片

In `Typora` and other md readers, this should be shown as 
图片

the md code like this:
```md
#### 选择 Select 

- 单目运算，限制一些属性的域（缩小集合）

- $\sigma_P(r):=\{t|t\in r \and P(t)\}$
```
just wedge the math formula between '$$'

ps: when I wrote math formula in Trilium and export to `.md` files, the formula was not shown correctly, due to the loss of '$$'.

### Error logs

_No response_

### PR DESCRIPTION
**Pull request by dousha**
The ability to typeset math expressions in markdown is now considered essential. Many other markdown-based note-taking software supports using TeX-like expressions for this, as demonstrated in #4387.

This PR adds proper support for importing math expressions from Markdown by leveraging the extension functionality of `marked`. A set of tokenizers is added to `marked` to parse these expressions and convert them into KaTeX-compliant HTML output.

Closes #4387.

### CODE REVIEW

**Comment by dousha** [comment]
Should #4417 be merged, we can just switch to using [marked-katex-extension](https://www.npmjs.com/package/marked-katex-extension), which lists `katex` as a dependency.

**Comment by zadam** [comment]
@dousha https://github.com/zadam/trilium/pull/4417 has been merged. Do you need to modify your PR now?

**Comment by dousha** [comment]
There are some modifications made to the original `marked-katex-extension`. Notably the ability to use `\( \)` and `\[ \]` for math expressions. I'll merge these modifications to `marked-katex-extension` first.

**Comment by eldertek** [comment]
Up

**Pull request closed without merging**
