### PR TITLE
Update JSDoc & API Docs

### PR DESCRIPTION
**Pull request by rauenzi**
This PR fixes a few issues with the JSDoc or makes improvements on the existing comments:
- Swapped `@property` to `@param` where appropriate
- Moved type descriptions to the description block so they aren't ignored
- Added the widgets (the ones available on `FrontendScriptApi` to the docs and added some additional comments for them
- Added custom types for attributes and notes to make it clear what types to expect.
- Added `api` as global for both frontend and backend to make it clear where the instances of the apis are found

I also separately worked on some potential improvements for the Docs like adding tutorials and information on the index pages. Is this something you'd be interested in seeing added to the Docs?

### CODE REVIEW

**Comment by zadam** [comment]
Thanks!

> I also separately worked on some potential improvements for the Docs like adding tutorials and information on the index pages. Is this something you'd be interested in seeing added to the Docs?

Do you mean to wiki? If interested, I can give you collaborator rights to be able to edit it ...

**Comment by rauenzi** [comment]
I actually meant to the JSDoc (see the images), but I could also add it to the wiki if that's what you'd prefer.

image
image

**Comment by rauenzi** [comment]
@zadam the reasoning behind using the wiki makes sense, just figured I would throw it out there as an idea. Would be happy to contribute some guides and info to the wiki though.

**Comment by rauenzi** [comment]
Hi @zadam I have a couple brief tutorials written focusing on widgets. Did you have any other topics you think should be covered via tutorial? I'm more than happy to add them to the wiki or give them to you to add there. Or I can put them into [Discussions](https://github.com/zadam/trilium/discussions) if you think that'd be a better place.

**Comment by zadam** [comment]
Sounds great, I've added you as collaborator, so you can edit the wiki.

TBH I don't have a good overview of what could be missing. For that an outside view might be valuable, perhaps asking in a discussion other people might be able to suggest some unclear topics worth explaining.

**Comment by rauenzi** [comment]
That's a good idea!

**Pull request merged**
