### PR TITLE
Implement user customizable keybindings

### PR DESCRIPTION
**Pull request by expelledboy**

### CODE REVIEW

**Comment by expelledboy** [comment]
FYI cant actually build the project, so kinda shooting in the dark.

**Comment by expelledboy** [comment]
Would love to have a working [shell.nix](https://github.com/DisciplinaOU/disciplina-student/blob/3f24dc5e8d0bd668d39dc8c4654dcf9a7ff32cf4/shell.nix) for reproducible dev environments. But still failing to get this to build on darwin, even in nix.

**Comment by PostPollux** [comment]
Have you tried using gitpod.io? This should give you a ready-to-code dev environment with one click:
https://gitpod.io/#https://github.com/zadam/trilium
or even with your stuff already applied:
https://gitpod.io/#https://github.com/zadam/trilium/pull/675

**Comment by zadam** [comment]
Hello, customizable keybindings is a planned feature in one of the next development versions (no ETA though). This PR is currently incomplete and looks also broken so I don't plan to merge it in this state.

**Pull request closed without merging**
